name: VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup VPS with SSH and latest ngrok
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server unzip curl

          # Start SSH service
          sudo service ssh start

          # Set root password
          echo "root:rootpass" | sudo chpasswd

          # Download latest ngrok v3
          NGROK_VER="3.7.0"
          curl -L -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok.zip
          chmod +x ngrok

          # Authenticate ngrok
          ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start ngrok TCP tunnel and print everything
          echo "Starting ngrok tunnel for SSH..."
          ./ngrok tcp 22 --region us

          # Keep workflow alive
          sleep infinity
