name: VPS

on:
  workflow_dispatch:  # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup VPS with SSH and ngrok
        run: |
          # Update system and install required packages
          sudo apt update -y
          sudo apt install -y openssh-server unzip curl

          # Start SSH service
          sudo service ssh start

          # Set root password
          echo "root:rootpass" | sudo chpasswd

          # Download ngrok
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip -o ngrok.zip
          chmod +x ngrok

          # Authenticate ngrok
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start ngrok TCP tunnel for SSH and print all output
          echo "Starting ngrok tunnel for SSH..."
          ./ngrok tcp 22 --region us

          # Keep workflow alive (optional if you want it to last forever)
          sleep infinity
