name: Free VPS

on:
  workflow_dispatch:   # run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install -y ngrok openssh-server

    - name: Auth ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Setup SSH
      run: |
        sudo service ssh start
        echo "root:rootpass" | sudo chpasswd
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh restart

    - name: Start ngrok tunnel
      run: |
        nohup ngrok tcp 22 --region us > ngrok.log &
        sleep 10
        echo "===================================="
        echo " COPY THIS SSH COMMAND INTO TERMUX ↓"
        echo
        awk '/tcp:\/\// {print "ssh root@"substr($2,7)}' ngrok.log | sed 's/:/ -p /'
        echo
        echo "Password: rootpass"
        echo "===================================="

    - name: Keep alive
      run: sleep 21600   # 6 hours max
