name: VPS

on:
  workflow_dispatch: # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ngrok & SSH
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server unzip curl

          # Enable SSH
          sudo service ssh start

          # Download ngrok
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip -o ngrok.zip
          chmod +x ngrok

          # Authenticate ngrok with your secret
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start ngrok tunnel for SSH (port 22)
          ./ngrok tcp 22 --region us > ngrok.log &
          sleep 8

          # Set root password
          echo "root:rootpass" | sudo chpasswd

          echo "===================================="
          echo " COPY THIS SSH COMMAND INTO TERMUX ↓"
          echo

          # Extract forwarding URL and format into SSH command
          ssh_cmd=$(grep -o "tcp://[0-9a-zA-Z\.]*:[0-9]*" ngrok.log | sed 's/tcp:\/\///' | sed 's/:/ -p /')
          echo "ssh root@${ssh_cmd}"
          echo
          echo "Password: rootpass"
          echo "===================================="

          # Keep workflow alive
          sleep infinity
